set(SRC_FILES
    Alcohol.cpp
    AmarettoSour.cpp
    CowboyShot.cpp
    CraftBeer.cpp
    Fireball.cpp
    Goldschlager.cpp
    Hefeweizen.cpp
    IPA.cpp
    Lager.cpp
    Margarita.cpp
    Martini.cpp
    Mojito.cpp
    Rum.cpp
    Stout.cpp
    Tequila.cpp
    Wildfire.cpp
)

set(INCLUDE_FILES
    Alcohol.h
    AmarettoSour.h
    CowboyShot.h
    CraftBeer.h
    Fireball.h
    Goldschlager.h
    Hefeweizen.h
    IPA.h
    Lager.h
    Margarita.h
    Martini.h
    Mojito.h
    Rum.h
    Stout.h
    Tequila.h
    Wildfire.h
)

set(TEST_FILES
    ut_CheckPoint1.cpp
    ut_CheckPoint2.cpp
    ut_CheckPoint3.cpp
)
